#!/bin/sh

#
# chkconfig:   2345 80 20
# description: Starts and stops a single mandrel instance on this system 
#

### BEGIN INIT INFO
# Provides: mandrel
# Required-Start: $network $named
# Required-Stop: $network $named
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: This service manages the mandrel daemon
# Description: Just... mandrel
### END INIT INFO

#
# Source function library.
#
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

prog="mandrel"

#
# Load default configuration for the application.
#
[ -e /etc/sysconfig/$prog ] &&. /etc/sysconfig/$prog

if [ "$1" = "start" ] || [ "$1" = "console" ]; then
    # Prepare stuff before launching the service
	if [ -n "$MAX_OPEN_FILES" ]; then
        ulimit -n $MAX_OPEN_FILES
    fi
fi

/usr/share/mandrel/bin/$prog $1