#!/bin/sh
#
# /etc/init.d/mandrel -- startup script for mandrel
#
### BEGIN INIT INFO
# Provides:          mandrel
# Required-Start:    $network $remote_fs $named
# Required-Stop:     $network $remote_fs $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts mandrel
# Description:       Starts mandrel
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=mandrel
DESC="mandrel Server"

#
# Source function library.
#
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

prog="mandrel"

#
# Load default configuration for the application.
#
[ -e /etc/sysconfig/$prog ] &&. /etc/sysconfig/$prog

if [ "$1" = "start" ] || [ "$1" = "console" ]; then
    # Prepare stuff before launching the service
	if [ -n "$MAX_OPEN_FILES" ]; then
        ulimit -n $MAX_OPEN_FILES
    fi
fi

/usr/share/mandrel/bin/$prog $1