spring:
  pidfile: worker.pid
  application:
    name: worker
    admin:
      enabled: false      
  cloud:
    zookeeper:
      enabled: true
      connectString: localhost:2181
      discovery:
        enabled: true
        root: /mandrel
  jmx:
    enabled: false
                        
server:
  port: 8070
