spring:
  pidfile: worker.pid
  application:
    name: worker
    admin:
      enabled: false      
  jmx:
    enabled: false

discovery:
  instanceHost: localhost
  zookeeper:
    enabled: true
    connectString: localhost:2181
    root: /mandrel
                            
transport:
  bindAddress: localhost
  port: 8091
                             
logging:
  console:
    enabled: true
    level: WARN
  level:
    org.springframework: INFO
    io.mandrel: DEBUG
    
management:
  context-path: /admin

endpoints:
  shutdown:
    enabled: true
  health:
    time-to-live: 5000
