environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App    

network:
    discovery:
        multicast:
            enabled: false

http:
    port: 8080

server:
    port: 8080
    #address:
    
spring:
    pidfile: application.pid
    groovy:
        template:
            check-template-location: false
    mustache:
        suffix: .html
    
graphite:
    enabled: false
    port: 2003
    host: localhost
    
logging:
    console:
        enabled: true
        level: WARN
    level:
        org.springframework: INFO
        io.mandrel: DEBUG
        io.mandrel.messaging: DEBUG
        
management:
    context-path: /admin
        
info:
    artifact: mandrel
    name: Mandrel
    description: The crawler at scale
    version: 0.0.1-SNAPSHOT

endpoints:
    shutdown:
        enabled: true
    health:
        time-to-live: 5000

