spring:
  pidfile: frontier.pid
  application:
    name: frontier
    admin:
      enabled: false    
  jmx:
    enabled: false

discovery:
  zookeeper:
    enabled: true
    connectString: localhost:2181
    root: /mandrel
    instanceHost: localhost
                            
server:
  port: 8090
  undertow:
    buffer-size: 16000
    buffers-per-region: 20
    direct-buffers: true
    io-threads: 4
    worker-threads: 32

logging:
  console:
    enabled: true
    level: WARN
  level:
    org.springframework: INFO
    io.mandrel: DEBUG
    
management:
  context-path: /admin

endpoints:
  shutdown:
    enabled: true
  health:
    time-to-live: 5000
