spring:
  pidfile: frontier.pid
  application:
    name: frontier
    admin:
      enabled: false    
  jmx:
    enabled: false

discovery:
  instanceHost: localhost
  zookeeper:
    enabled: true
    connectString: localhost:2181
    root: /mandrel

transport:
  port: 8092
  bindAddress: localhost
                                
logging:
  console:
    enabled: true
    level: WARN
  level:
    org.springframework: INFO
    io.mandrel: DEBUG
    
management:
  context-path: /admin

endpoints:
  shutdown:
    enabled: true
  health:
    time-to-live: 5000
